# Generated by Django 4.1.7 on 2023-06-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_is_checked_out_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_checked_out',
        ),
    ]
