# Generated by Django 4.2.2 on 2023-06-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_cart_is_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(to='cart.cartitem'),
        ),
    ]
