# Generated by Django 4.2.2 on 2023-06-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_stock'),
        ('cart', '0007_order_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
            preserve_default=False,
        ),
    ]
