# Generated by Django 4.2.2 on 2023-06-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product_name',
        ),
    ]
