# Generated by Django 4.2.2 on 2023-06-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_rename_name_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.userprofile'),
            preserve_default=False,
        ),
    ]
