# Generated by Django 4.2.2 on 2023-06-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
